// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Strategy struct {
	ID             int32                 `json:"id"`
	UserID         sql.NullInt32         `json:"user_id"`
	Name           string                `json:"name"`
	Indicators     pqtype.NullRawMessage `json:"indicators"`
	Buyconditions  pqtype.NullRawMessage `json:"buyconditions"`
	Sellconditions pqtype.NullRawMessage `json:"sellconditions"`
	CreatedAt      sql.NullTime          `json:"created_at"`
	UpdatedAt      sql.NullTime          `json:"updated_at"`
}

type User struct {
	ID             int32        `json:"id"`
	Name           string       `json:"name"`
	Email          string       `json:"email"`
	HashedPassword string       `json:"hashed_password"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
}
