// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateStrategy(ctx context.Context, arg CreateStrategyParams) (Strategy, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteStrategy(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetStrategiesByUser(ctx context.Context, userID sql.NullInt32) ([]Strategy, error)
	GetUser(ctx context.Context, email string) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
